# Generated by Django 3.2.3 on 2021-09-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, choices=[('Music production', 'Music Production'), ('Software', 'Softwarte'), ('Computer Gaming', 'Computer Gaming')], max_length=100, null=True)),
            ],
        ),
    ]
